pipeline {
    agent any

    environment {
        COMPOSE_FILE = 'compose.yml'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Tawunchai/serverless-cloud.git'
            }
        }

        stage('Stop Old Containers ') {
            steps {
                sh 'docker-compose -f ${COMPOSE_FILE} down || true'
            }
        }

        stage('Build & Start Containers') {
            steps {
                sh 'docker-compose -f ${COMPOSE_FILE} build'
                sh 'docker-compose -f ${COMPOSE_FILE} up -d'
            }
        }
    }
}
